# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GymLog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GymLog
  pod 'FSCalendar', '~> 2.8'
end
